config/routes.rb
Rails.application.routes.draw do
  # Makes 'localhost/welcome/index' page available
  # get 'welcome/index' 

  # Renders 'welcome/index.html' as default path (localhost/)
  root 'welcome#index'

  resources "entries"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    def index
        @entries = Entry.all
    end

    def show
        @entry = Entry.find(params[:id])
    end

    def new
        
    end
    
    def create
        entry_params = params["entry"].permit("title","contents")
        entry = Entry.create(entry_params)
        redirect_to(entry_path(entry))
    end

    def edit
        @entry = Entry.find(params[:id])
    end
    
    def update
        entry_params = params["entry"].permit("title","contents")
        entry = Entry.find(params[:id])
        entry.update(entry_params)
        redirect_to(entry_path(entry))
    end
    
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

    # Declares "instance variables" (@), accessable by controler & view
    @websites = [
      ["http://railsgirls.com", "Rails Girls"],
      ["http://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
      ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
    ]

    @entries = Entry.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%# Loop "for" for the entry data %>
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<hr>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
<p><%= link_to("[+] Add new entry", new_entry_path) %><p>

<hr>

<% for entry in @entries %>
    <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
    <p><%= entry.date %></p>
    <p><%= entry.contents %></p>
<% end %>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2><%= @entry.title %></h2>
<p><%= @entry.date %></p>
<p><%= @entry.contents %></p>
<br>
<p><%= link_to("[*] Edit this entry", edit_entry_path(@entry)) %></p>
<hr>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Little Webapp: Coding is Magic</title>
</head>
<body>
    <h1>My Rails Girls Diary</h1>
    <div>
       <% for entry in @entries %>
          <h2><%= entry.title%></h2>
          <p><%= entry.date %></p>
          <p><%= entry.contents %></p>
        <% end %>
    </div>
    <div>
        <h1>My favorite websites</h1>
        <ul>
            <% for url, name in @websites %>
                <li><a href="<%=url%>"><%=name%></a></li>
            <% end %>
        </ul>
    </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />
</body>
</html>